"Can you catch ANY!?"
"You SUCK"
"Suck it, loser!"
"I'm doing this to help you. Trust me!"
"Fag"
"What, gonna go cry to some big strong zebra?"
"If FicFic could see what you've become..."
"wtf man why r u moaning"
"There's no WAY this joke is old"
"STFU"
"You enjoy catching balls, don't you"
"Try harder, tard"
"You'll thank me for this"
"Fourty-eight"
"no srsly stap moaning. it's creepy"